PREFIX ub:   <http://example.org#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE { <http://www.Department0.University0.edu/UndergraduateStudent91> ub:memberOf ?v1. { ?v2 ub:headOf ?v1. } UNION { ?v2 ub:worksFor ?v1. } ?v2 ub:undergraduateDegreeFrom ?v3.
?v4 ub:doctoralDegreeFrom ?v3. ?v5 ub:publicationAuthor ?v2.
{ ?v6 ub:headOf ?v1. } UNION { ?v6 ub:worksFor ?v1. }
{ ?v2 ub:headOf ?v7. } UNION { ?v2 ub:worksFor ?v7. } ?v7 ub:name ?v8. }