PREFIX ub:   <http://example.org#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
{ ?st ub:teachingAssistantOf ?course.
OPTIONAL { ?st ub:takesCourse ?course2. ?pub1 ub:publicationAuthor ?st. } } { ?prof ub:teacherOf ?course. ?st ub:advisor ?prof.
OPTIONAL { ?prof ub:researchInterest ?resint.
?pub2 ub:publicationAuthor ?prof. } } }