PREFIX ub:   <http://example.org#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
?x ub:worksFor <http://www.Department0.University12.edu>.
?x a ub:FullProfessor.
OPTIONAL { ?x ub:emailAddress ?y1. ?x ub:telephone ?y2. ?x ub:name ?y3. } }