PREFIX purl:   <http://purl.org/dc/terms/>
PREFIX nsprov:   <http://www.w3.org/ns/prov#>
PREFIX georss:   <http://www.georss.org/georss/>
PREFIX dbo:   <http://dbpedia.org/ontology/>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbp:   <http://dbpedia.org/property/>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
PREFIX dbr:   <http://dbpedia.org/resource/>
PREFIX geo:   <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>

SELECT * WHERE {
?v1 dbo:wikiPageWikiLink dbr:Category:Cell_biology.
{ ?v2 foaf:primaryTopic ?v1. } UNION { ?v1 foaf:isPrimaryTopicOf ?v2. }
{ ?v2 foaf:primaryTopic ?v3. } UNION { ?v3 foaf:isPrimaryTopicOf ?v2. } ?v3 dbo:wikiPageWikiLink ?v1. OPTIONAL{ { ?v2 foaf:primaryTopic ?v4. } UNION { ?v4 foaf:isPrimaryTopicOf ?v2. } }
OPTIONAL{ ?v5 dbo:phylum ?v3. ?v6 dbo:phylum ?v3.
OPTIONAL{ { ?v7 foaf:primaryTopic ?v5. }
UNION { ?v5 foaf:isPrimaryTopicOf ?v7. } } } }